import APJP
import APJP.HTTP
import APJP.HTTPS

APJP.HTTP.APJP_KEY = ''
APJP.HTTP.APJP_REMOTE_HTTP_SERVER_RESPONSE_PROPERTY_KEY[0] = ''
APJP.HTTP.APJP_REMOTE_HTTP_SERVER_RESPONSE_PROPERTY_VALUE[0] = ''
APJP.HTTP.APJP_REMOTE_HTTP_SERVER_RESPONSE_PROPERTY_KEY[1] = ''
APJP.HTTP.APJP_REMOTE_HTTP_SERVER_RESPONSE_PROPERTY_VALUE[1] = ''
APJP.HTTP.APJP_REMOTE_HTTP_SERVER_RESPONSE_PROPERTY_KEY[2] = ''
APJP.HTTP.APJP_REMOTE_HTTP_SERVER_RESPONSE_PROPERTY_VALUE[2] = ''
APJP.HTTP.APJP_REMOTE_HTTP_SERVER_RESPONSE_PROPERTY_KEY[3] = ''
APJP.HTTP.APJP_REMOTE_HTTP_SERVER_RESPONSE_PROPERTY_VALUE[3] = ''
APJP.HTTP.APJP_REMOTE_HTTP_SERVER_RESPONSE_PROPERTY_KEY[4] = ''
APJP.HTTP.APJP_REMOTE_HTTP_SERVER_RESPONSE_PROPERTY_VALUE[4] = ''

APJP.HTTPS.APJP_KEY = ''
APJP.HTTPS.APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_KEY[0] = ''
APJP.HTTPS.APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_VALUE[0] = ''
APJP.HTTPS.APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_KEY[1] = ''
APJP.HTTPS.APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_VALUE[1] = ''
APJP.HTTPS.APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_KEY[2] = ''
APJP.HTTPS.APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_VALUE[2] = ''
APJP.HTTPS.APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_KEY[3] = ''
APJP.HTTPS.APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_VALUE[3] = ''
APJP.HTTPS.APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_KEY[4] = ''
APJP.HTTPS.APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_VALUE[4] = ''

application = APJP.application