<?php
// EXAMPLE: $APJP_KEY = '1AJyx7s4Vs8afWY4';
$APJP_KEY = '';
$APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_KEY = array();
$APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_VALUE = array();
$APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_KEY[0] = '';
$APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_VALUE[0] = '';
$APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_KEY[1] = '';
$APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_VALUE[1] = '';
$APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_KEY[2] = '';
$APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_VALUE[2] = '';
$APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_KEY[3] = '';
$APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_VALUE[3] = '';
$APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_KEY[4] = '';
$APJP_REMOTE_HTTPS_SERVER_RESPONSE_PROPERTY_VALUE[4] = '';
?>